
    alter table Boards 
        drop constraint FK76E9DA6D4F7DBDC9;

    alter table TaskLists 
        drop constraint FK812A08F0B01DFBDC;

    alter table Tasks 
        drop constraint FK4CD8B6E611356;

    alter table Tasks 
        drop constraint FK4CD8B6E3A954BE7;

    alter table WorkUser 
        drop constraint FK5EE9A9CF481B9CA;

    alter table WorkUser 
        drop constraint FK5EE9A9CA1A5A78A;

    alter table group_users 
        drop constraint FK41CACC48F481B9CA;

    alter table group_users 
        drop constraint FK41CACC48C8FB8B6A;

    alter table users 
        drop constraint FK6A68E08AA851A11;

    alter table users 
        drop constraint FK6A68E08F481B9CA;

    drop table Boards if exists;

    drop table Groups if exists;

    drop table TaskLists if exists;

    drop table Tasks if exists;

    drop table Users if exists;

    drop table WorkUser if exists;

    drop table group_users if exists;

    drop table users if exists;

    create table Boards (
        id bigint generated by default as identity (start with 1),
        access varchar(255),
        description varchar(255),
        name varchar(255),
        creator_id bigint,
        primary key (id)
    );

    create table Groups (
        id bigint generated by default as identity (start with 1),
        access varchar(255),
        admin tinyblob,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table TaskLists (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        board bigint,
        primary key (id)
    );

    create table Tasks (
        id bigint generated by default as identity (start with 1),
        creation date,
        description varchar(255),
        dueDate date,
        group tinyblob,
        name varchar(255),
        state integer,
        creator bigint,
        tasklist bigint,
        primary key (id)
    );

    create table Users (
        id bigint generated by default as identity (start with 1),
        mail varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id),
        unique (name),
        unique (mail)
    );

    create table WorkUser (
        hours double precision,
        task_id bigint,
        user_id bigint,
        primary key (task_id, user_id)
    );

    create table group_users (
        group_id bigint not null,
        user_id bigint not null,
        primary key (group_id, user_id)
    );

    create table users (
        id bigint not null,
        user_id bigint not null,
        primary key (id, user_id)
    );

    alter table Boards 
        add constraint FK76E9DA6D4F7DBDC9 
        foreign key (creator_id) 
        references Users;

    alter table TaskLists 
        add constraint FK812A08F0B01DFBDC 
        foreign key (board) 
        references Boards;

    alter table Tasks 
        add constraint FK4CD8B6E611356 
        foreign key (tasklist) 
        references TaskLists;

    alter table Tasks 
        add constraint FK4CD8B6E3A954BE7 
        foreign key (creator) 
        references Users;

    alter table WorkUser 
        add constraint FK5EE9A9CF481B9CA 
        foreign key (user_id) 
        references Users;

    alter table WorkUser 
        add constraint FK5EE9A9CA1A5A78A 
        foreign key (task_id) 
        references Tasks;

    alter table group_users 
        add constraint FK41CACC48F481B9CA 
        foreign key (user_id) 
        references Users;

    alter table group_users 
        add constraint FK41CACC48C8FB8B6A 
        foreign key (group_id) 
        references Groups;

    alter table users 
        add constraint FK6A68E08AA851A11 
        foreign key (id) 
        references Boards;

    alter table users 
        add constraint FK6A68E08F481B9CA 
        foreign key (user_id) 
        references Users;
